activation: gelu
anormly_ratio: 0.5
batch_size: 64
d_ff: 64
d_model: 16
data_path: ./dataset/SAW
dataset: SAW
dropout: 0.1
e_layers: 3
input_c: 1
isLabelled: true
lr: 1e-3
mode: test
model_save_path: checkpoints
n_heads: 4
num_epochs: 10
output_c: 1
pretrained_model: None
seed: 42
win_size: 110
